FROM balenalib/armv7hf-alpine:3.12

ADD RFM69GwToInfluxBridge.py /bin/
ADD rfm69gwtoinfluxbridge.conf /etc/
ADD rfm69gwtoinfluxbridge.conf /etc/rfm69gwtoinfluxbridge.conf.default

RUN [ "cross-build-start" ]

RUN install_packages python3 py3-pip

RUN pip install influxdb paho.mqtt

RUN [ "cross-build-end" ]  

CMD ["/usr/bin/python3", "/bin/RFM69GwToInfluxBridge.py"]
