FROM python:3.7-slim AS build

WORKDIR /app
COPY RFM69GwToInfluxBridge.py /app/
COPY rfm69gwtoinfluxbridge.conf /app/
COPY rfm69gwtoinfluxbridge.conf /app/rfm69gwtoinfluxbridge.conf.default
COPY requirements.txt /app/

RUN pip3 install -r /app/requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build /app /app
COPY --from=build /usr/local/lib/python3.7/site-packages/ /usr/lib/python3.7/.
WORKDIR /app

CMD ["/app/RFM69GwToInfluxBridge.py"]
