FROM balenalib/armv7hf-alpine:3.12

WORKDIR /app
COPY RFM69GwToInfluxBridge.py /app/
COPY rfm69gwtoinfluxbridge.conf /app/
COPY rfm69gwtoinfluxbridge.conf /app/rfm69gwtoinfluxbridge.conf.default
COPY requirements.txt /app/

RUN [ "cross-build-start" ]

RUN install_packages python3 py3-pip \
    && pip3 install -r /app/requirements.txt

RUN [ "cross-build-end" ]  

CMD ["/usr/bin/python3", "/bin/RFM69GwToInfluxBridge.py"]
